import { Mongo } from 'meteor/mongo'
Colleges2 = new Mongo.Collection( 'colleges2' );
 if ( Meteor.isServer ) {
  Colleges2._ensureIndex( { name: 1, location: 1, SAT: 1 } );
}

Colleges2.allow({
  insert: () => false,
  update: () => false,
  remove: () => false
});

Colleges2.deny({
  insert: () => true,
  update: () => true,
  remove: () => true
});

let Colleges2Schema = new SimpleSchema({
  'name': {
    type: String,
    label: 'The name of the college.'
  },
  'location': {
    type: String,
    label: 'The location of the college.'
  },
  'SAT': {
    type: String,
    label: 'The SAT score of the college.'
  }
});

Colleges2.attachSchema( Colleges2Schema );

/* Colleges2.insert({name:"Amherst College", location:"New England", SAT:"1430-1570"});
Colleges2.insert({name:"Babson College", location:"New England", SAT:"1260-1450"});
Colleges2.insert({name:"Bates College", location:"New England", SAT:"1270-1470"}); */





/*Colleges2.insert({name:"Amherst College", location:"New England", SAT:"1430–1570"});
Colleges2.insert({name:"Babson College", location:"New England", SAT:"1260–1450"});
Colleges2.insert({name:"Bates College", location:"New England", SAT:"1270–1470"});
Colleges2.insert({name:"Bennington College", location:"New England", SAT:"1230–1440"});
Colleges2.insert({name:"Bentley University", location:"New England", SAT:"1230–1410"});
Colleges2.insert({name:"Boston College", location:"New England", SAT:"1340–1510"});
Colleges2.insert({name:"Boston University", location:"New England", SAT:"1290–1480"});
Colleges2.insert({name:"Bowdoin College", location:"New England", SAT:"1450–1560"});
Colleges2.insert({name:"Brandeis University", location:"New England", SAT:"1360–1520"});
Colleges2.insert({name:"Brown University", location:"New England", SAT:"1440–1580"});
Colleges2.insert({name:"Clark University", location:"New England", SAT:"1260–1410"});
Colleges2.insert({name:"Colby College", location:"New England", SAT:"1310–1490"});
Colleges2.insert({name:"College of the Holy Cross", location:"New England", SAT:"1300–1450"});
Colleges2.insert({name:"Connecticut College", location:"New England", SAT:"1290–1460"});
Colleges2.insert({name:"Dartmouth College", location:"New England", SAT:"1410–1580"});
Colleges2.insert({name:"Emerson College", location:"New England", SAT:"1220–1380"});
Colleges2.insert({name:"Fairfield University", location:"New England", SAT:"1180–1340"});
Colleges2.insert({name:"Harvard University", location:"New England", SAT:"1480–1600"});
Colleges2.insert({name:"Massachusetts Institute of Technology", location:"New England", SAT:"1480–1580"});
Colleges2.insert({name:"Middlebury College", location:"New England", SAT:"1340–1520"});
Colleges2.insert({name:"Mount Holyoke College", location:"New England", SAT:"1310–1510"});
Colleges2.insert({name:"Northeastern University", location:"New England", SAT:"1410–1540"});
Colleges2.insert({name:"Providence College", location:"New England", SAT:"1140–1330"});
Colleges2.insert({name:"Quinnipiac University", location:"New England", SAT:"1100–1290"});
Colleges2.insert({name:"Rhode Island School of Design", location:"New England", SAT:"1200–1460"});
Colleges2.insert({name:"Simmons College", location:"New England", SAT:"1160–1330"});
Colleges2.insert({name:"Smith College", location:"New England", SAT:"1320–1500"});
Colleges2.insert({name:"St. Michael's College", location:"New England", SAT:"1150–1330"});
Colleges2.insert({name:"Stonehill College", location:"New England", SAT:"1100–1300"});
Colleges2.insert({name:"Trinity College (Hartford)", location:"New England", SAT:"1230–1420"});
Colleges2.insert({name:"Tufts University", location:"New England", SAT:"1440–1550"});
Colleges2.insert({name:"United States Coast Guard Academy", location:"New England", SAT:"1250–1410"});
Colleges2.insert({name:"University of Connecticut", location:"New England", SAT:"1220–1420"});
Colleges2.insert({name:"University of Massachusetts— Amherst", location:"New England", SAT:"1200–1380"});
Colleges2.insert({name:"University of New Hampshire", location:"New England", SAT:"1090–1280"});
Colleges2.insert({name:"University of Vermont", location:"New England", SAT:"1170–1360"});
Colleges2.insert({name:"Wellesley College", location:"New England", SAT:"1360–1530"});
Colleges2.insert({name:"Wesleyan University", location:"New England", SAT:"1330–1520"});
Colleges2.insert({name:"Williams College", location:"New England", SAT:"1410–1570"});
Colleges2.insert({name:"Worcester Polytechnic Institute", location:"New England", SAT:"1290–1470"});
Colleges2.insert({name:"Yale University", location:"New England", SAT:"1480–1600"});

Colleges2.insert({name:"Adelphi University", location:"Mid-Atlantic", SAT:"1100–1300"});
Colleges2.insert({name:"Allegheny College", location:"Mid-Atlantic", SAT:"1130–1340"});
Colleges2.insert({name:"American University", location:"Mid-Atlantic", SAT:"1220–1390"});
Colleges2.insert({name:"Bard College", location:"Mid-Atlantic", SAT:"1230–1450"});
Colleges2.insert({name:"Barnard College", location:"Mid-Atlantic", SAT:"1330–1490"});
Colleges2.insert({name:"Binghamton University— SUNY", location:"Mid-Atlantic", SAT:"1280–1440"});
Colleges2.insert({name:"Bryn Mawr College", location:"Mid-Atlantic", SAT:"1320–1510"});
Colleges2.insert({name:"Bucknell University", location:"Mid-Atlantic", SAT:"1290–1460"});
Colleges2.insert({name:"Carnegie Mellon University", location:"Mid-Atlantic", SAT:"1440–1570"});
Colleges2.insert({name:"Clarkson University", location:"Mid-Atlantic", SAT:"1160–1360"});
Colleges2.insert({name:"Colgate University", location:"Mid-Atlantic", SAT:"1310–1520"});
Colleges2.insert({name:"College of New Jersey", location:"Mid-Atlantic", SAT:"1200–1400"});
Colleges2.insert({name:"Columbia University", location:"Mid-Atlantic", SAT:"1460–1590"});
Colleges2.insert({name:"Cooper Union", location:"Mid-Atlantic", SAT:"1330–1530"});
Colleges2.insert({name:"Cornell University", location:"Mid-Atlantic", SAT:"1410–1570"});
Colleges2.insert({name:"CUNY— Baruch College", location:"Mid-Atlantic", SAT:"1190–1400"});
Colleges2.insert({name:"Dickinson College", location:"Mid-Atlantic", SAT:"1270–1450"});
Colleges2.insert({name:"Drew University", location:"Mid-Atlantic", SAT:"1090–1290"});
Colleges2.insert({name:"Drexel University", location:"Mid-Atlantic", SAT:"1170–1390"});
Colleges2.insert({name:"Duquesne University", location:"Mid-Atlantic", SAT:"1120–1300"});
Colleges2.insert({name:"Fordham University", location:"Mid-Atlantic", SAT:"1230–1420"});
Colleges2.insert({name:"Franklin and Marshall College", location:"Mid-Atlantic", SAT:"1290–1460"});
Colleges2.insert({name:"Gallaudet University", location:"Mid-Atlantic", SAT:"870–1040"});
Colleges2.insert({name:"George Washington University", location:"Mid-Atlantic", SAT:"1270–1460"});
Colleges2.insert({name:"Georgetown University", location:"Mid-Atlantic", SAT:"1390–1560"});
Colleges2.insert({name:"Gettysburg College", location:"Mid-Atlantic", SAT:"1270–1430"});
Colleges2.insert({name:"Goucher College", location:"Mid-Atlantic", SAT:"1070–1290"});
Colleges2.insert({name:"Hamilton College", location:"Mid-Atlantic", SAT:"1370–1520"});
Colleges2.insert({name:"Haverford College", location:"Mid-Atlantic", SAT:"1400–1560"});
Colleges2.insert({name:"Hobart and William Smith Colleges2", location:"Mid-Atlantic", SAT:"1200–1390"});
Colleges2.insert({name:"Hofstra University", location:"Mid-Atlantic", SAT:"1120–1300"});
Colleges2.insert({name:"Howard University", location:"Mid-Atlantic", SAT:"1070–1290"});
Colleges2.insert({name:"Ithaca College", location:"Mid-Atlantic", SAT:"1170–1360"});
Colleges2.insert({name:"Johns Hopkins University", location:"Mid-Atlantic", SAT:"1470–1580"});
Colleges2.insert({name:"Lafayette College", location:"Mid-Atlantic", SAT:"1280–1460"});
Colleges2.insert({name:"Lehigh University", location:"Mid-Atlantic", SAT:"1300–1480"});
Colleges2.insert({name:"Loyola University Maryland", location:"Mid-Atlantic", SAT:"1180–1360"});
Colleges2.insert({name:"Marist College", location:"Mid-Atlantic", SAT:"1170–1340"});
Colleges2.insert({name:"Muhlenberg College", location:"Mid-Atlantic", SAT:"1200–1410"});
Colleges2.insert({name:"New Jersey Institute of Technology", location:"Mid-Atlantic", SAT:"1150–1380"});
Colleges2.insert({name:"New School", location:"Mid-Atlantic", SAT:"1080–1320"});
Colleges2.insert({name:"New York University", location:"Mid-Atlantic", SAT:"1320-1500"});

Colleges2.insert({name:"Penn State University— University Park", location:"Mid-Atlantic", SAT:"1170–1380"});
Colleges2.insert({name:"Pratt Institute", location:"Mid-Atlantic", SAT:"1150–1370"});
Colleges2.insert({name:"Princeton University", location:"Mid-Atlantic", SAT:"1460–1600"});
Colleges2.insert({name:"Rensselaer Polytechnic Institute", location:"Mid-Atlantic", SAT:"1370–1540"});
Colleges2.insert({name:"Rochester Institute of Technology", location:"Mid-Atlantic", SAT:"1180–1390"});
Colleges2.insert({name:"Rutgers— New Brunswick", location:"Mid-Atlantic", SAT:"1180–1400"});
Colleges2.insert({name:"Rutgers— Newark", location:"Mid-Atlantic", SAT:"1030–1210"});
Colleges2.insert({name:"Sarah Lawrence College", location:"Mid-Atlantic", SAT:"1230–1430"});
Colleges2.insert({name:"Seton Hall University", location:"Mid-Atlantic", SAT:"1120–1300"});
Colleges2.insert({name:"Siena College", location:"Mid-Atlantic", SAT:"1100–1290"});
Colleges2.insert({name:"Skidmore College", location:"Mid-Atlantic", SAT:"1190–1410"});
Colleges2.insert({name:"St. John Fisher College", location:"Mid-Atlantic", SAT:"1080–1240"});
Colleges2.insert({name:"St. John's College Annapolis", location:"Mid-Atlantic", SAT:"1260–1470"});
Colleges2.insert({name:"St. John's University (NY)", location:"Mid-Atlantic", SAT:"1030–1240"});
Colleges2.insert({name:"St. Lawrence University", location:"Mid-Atlantic", SAT:"1170–1380"});
Colleges2.insert({name:"St. Mary's College of Maryland", location:"Mid-Atlantic", SAT:"1110–1320"});
Colleges2.insert({name:"Stevens Institute of Technology", location:"Mid-Atlantic", SAT:"1330–1480"});
Colleges2.insert({name:"Stony Brook University— SUNY", location:"Mid-Atlantic", SAT:"1220–1450"});
Colleges2.insert({name:"SUNY—Environmental Science and Forestry", location:"Mid-Atlantic", SAT:"1160–1340"});
Colleges2.insert({name:"SUNY— Geneseo", location:"Mid-Atlantic", SAT:"1170–1350"});
Colleges2.insert({name:"Susquehanna University", location:"Mid-Atlantic", SAT:"1100–1280"});
Colleges2.insert({name:"Swarthmore College", location:"Mid-Atlantic", SAT:"1420–1560"});
Colleges2.insert({name:"Syracuse University", location:"Mid-Atlantic", SAT:"1150–1370"});
Colleges2.insert({name:"Temple University", location:"Mid-Atlantic", SAT:"1090–1300"});
Colleges2.insert({name:"The Catholic University of America", location:"Mid-Atlantic", SAT:"1100–1290"});
Colleges2.insert({name:"Union College (Schenectady, NY)", location:"Mid-Atlantic", SAT:"1310–1470"});
Colleges2.insert({name:"United States Military Academy", location:"Mid-Atlantic", SAT:"1240–1440"});
Colleges2.insert({name:"United States Naval Academy", location:"Mid-Atlantic", SAT:"1250–1460"});
Colleges2.insert({name:"University at Albany— SUNY", location:"Mid-Atlantic", SAT:"1090–1240"});
Colleges2.insert({name:"University at Buffalo— SUNY", location:"Mid-Atlantic", SAT:"1110–1310"});
Colleges2.insert({name:"University of Delaware", location:"Mid-Atlantic", SAT:"1180–1380"});
Colleges2.insert({name:"University of Maryland— College Park", location:"Mid-Atlantic", SAT:"1280–1500"});
Colleges2.insert({name:"University of Pennsylvania", location:"Mid-Atlantic", SAT:"1450–1580"});
Colleges2.insert({name:"University of Pittsburgh", location:"Mid-Atlantic", SAT:"1250–1430"});
Colleges2.insert({name:"University of Rochester", location:"Mid-Atlantic", SAT:"1320–1500"});
Colleges2.insert({name:"Ursinus College", location:"Mid-Atlantic", SAT:"1130–1330"});
Colleges2.insert({name:"Vassar College", location:"Mid-Atlantic", SAT:"1400–1530"});
Colleges2.insert({name:"Villanova University", location:"Mid-Atlantic", SAT:"1280–1470"});
Colleges2.insert({name:"Virginia Polytechnic Institute", location:"Mid-Atlantic", SAT:"1180–1390"});
Colleges2.insert({name:"Washington and Jefferson College", location:"Mid-Atlantic", SAT:"1110–1300"});
Colleges2.insert({name:"Washington College", location:"Mid-Atlantic", SAT:"1120–1340"});
Colleges2.insert({name:"Yeshiva University", location:"Mid-Atlantic", SAT:"1190–1420"});

Colleges2.insert({name:"Abilene Christian University", location:"South", SAT:"1070–1270"});
Colleges2.insert({name:"Agnes Scott College", location:"South", SAT:"1150–1380"});
Colleges2.insert({name:"Appalachian State University", location:"South", SAT:"1130–1300"});
Colleges2.insert({name:"Auburn University", location:"South", SAT:"1140–1320"});
Colleges2.insert({name:"Austin College", location:"South", SAT:"1150–1350"});
Colleges2.insert({name:"Baylor University", location:"South", SAT:"1200–1390"});
Colleges2.insert({name:"Berea College", location:"South", SAT:"1110–1290"});
Colleges2.insert({name:"Berry College", location:"South", SAT:"1140–1330"});
Colleges2.insert({name:"Birmingham– Southern College", location:"South", SAT:"1070–1300"});
Colleges2.insert({name:"Centre College", location:"South", SAT:"1170–1460"});
Colleges2.insert({name:"Christopher Newport University", location:"South", SAT:"1140–1320"});
Colleges2.insert({name:"Clemson University", location:"South", SAT:"1230–1420"});
Colleges2.insert({name:"College of Charleston", location:"South", SAT:"1100–1290"});
Colleges2.insert({name:"College of William and Mary", location:"South", SAT:"1330–1510"});
Colleges2.insert({name:"Davidson College", location:"South", SAT:"1320–1500"});
Colleges2.insert({name:"Duke University", location:"South", SAT:"1450–1580"});
Colleges2.insert({name:"Elon University", location:"South", SAT:"1210–1390"});
Colleges2.insert({name:"Embry– Riddle Aeronautical University", location:"South", SAT:"1090–1310"});
Colleges2.insert({name:"Emory University", location:"South", SAT:"1360–1520"});
Colleges2.insert({name:"Florida Institute of Technology", location:"South", SAT:"1100–1330"});
Colleges2.insert({name:"Florida State University", location:"South", SAT:"1200–1350"});
Colleges2.insert({name:"Furman University", location:"South", SAT:"1210–1410"});
Colleges2.insert({name:"George Mason University", location:"South", SAT:"1120–1310"});
Colleges2.insert({name:"Georgia Institute of Technology", location:"South", SAT:"1390–1530"});
Colleges2.insert({name:"Hampden– Sydney College", location:"South", SAT:"1070–1270"});
Colleges2.insert({name:"Hampton University", location:"South", SAT:"990–1170"});
Colleges2.insert({name:"Hendrix College", location:"South", SAT:"1150–1390"});
Colleges2.insert({name:"High Point University", location:"South", SAT:"1090–1270"});
Colleges2.insert({name:"Hollins University", location:"South", SAT:"1050–1250"});
Colleges2.insert({name:"James Madison University", location:"South", SAT:"1120–1300"});
Colleges2.insert({name:"John Brown University", location:"South", SAT:"1100–1310"});
Colleges2.insert({name:"Lipscomb University", location:"South", SAT:"1110–1320"});
Colleges2.insert({name:"Louisiana State University— Baton Rouge", location:"South", SAT:"1100–1320"});
Colleges2.insert({name:"Loyola University New Orleans", location:"South", SAT:"1080–1300"});
Colleges2.insert({name:"Mercer University", location:"South", SAT:"1150–1350"});
Colleges2.insert({name:"Millsaps College", location:"South", SAT:"1110–1330"});
Colleges2.insert({name:"Mississippi State University", location:"South", SAT:"1030–1320"});
Colleges2.insert({name:"Morehouse College", location:"South", SAT:"970–1190"});
Colleges2.insert({name:"New College of Florida", location:"South", SAT:"1240–1430"});
Colleges2.insert({name:"North Carolina State University— Raleigh", location:"South", SAT:"1230–1400"});
Colleges2.insert({name:"Oklahoma State University", location:"South", SAT:"1060–1280"});
Colleges2.insert({name:"Presbyterian College (SC)", location:"South", SAT:"1040–1270"});
Colleges2.insert({name:"Queens University of Charlotte", location:"South", SAT:"1010–1230"});
Colleges2.insert({name:"Randolph– Macon College", location:"South", SAT:"1060–1260"});

Colleges2.insert({name:"Rhodes College", location:"South", SAT:"1260–1460"});
Colleges2.insert({name:"Rice University", location:"South", SAT:"1460–1580"});
Colleges2.insert({name:"Rollins College", location:"South", SAT:"1190–1390"});
Colleges2.insert({name:"Samford University", location:"South", SAT:"1090–1300"});
Colleges2.insert({name:"Sewanee— University of the South", location:"South", SAT:"1210–1380"});
Colleges2.insert({name:"Southern Methodist University", location:"South", SAT:"1290–1480"});
Colleges2.insert({name:"Southwestern University", location:"South", SAT:"1110–1330"});
Colleges2.insert({name:"Spelman College", location:"South", SAT:" 990–1180"});
Colleges2.insert({name:"Stetson University", location:"South", SAT:"1150–1320"});
Colleges2.insert({name:"Texas A&M University— College Station", location:"South", SAT:"1130–1380"});
Colleges2.insert({name:"Texas Christian University", location:"South", SAT:"1160–1350"});
Colleges2.insert({name:"Texas Lutheran University", location:"South", SAT:"1000–1200"});
Colleges2.insert({name:"The Citadel", location:"South", SAT:"1070–1260"});
Colleges2.insert({name:"Transylvania University", location:"South", SAT:"1120–1370"});
Colleges2.insert({name:"Trinity University", location:"South", SAT:"1230–1420"});
Colleges2.insert({name:"Tulane University", location:"South", SAT:"1320–1470"});
Colleges2.insert({name:"University of Alabama", location:"South", SAT:"1070–1310"});
Colleges2.insert({name:"University of Arkansas", location:"South", SAT:"1080–1300"});
Colleges2.insert({name:"University of Dallas", location:"South", SAT:"1220–1430"});
Colleges2.insert({name:"University of Florida", location:"South", SAT:"1250–1430"});
Colleges2.insert({name:"University of Georgia", location:"South", SAT:"1220–1400"});
Colleges2.insert({name:"University of Kentucky", location:"South", SAT:"1080–1330"});
Colleges2.insert({name:"University of Mary Washington", location:"South", SAT:"1090–1270"});
Colleges2.insert({name:"University of Miami", location:"South", SAT:"1270–1450"});
Colleges2.insert({name:"University of Mississippi", location:"South", SAT:"1040–1250"});
Colleges2.insert({name:"University of North Carolina— Chapel Hill", location:"South", SAT:"1280–1460"});
Colleges2.insert({name:"University of North Carolina— Wilmington", location:"South", SAT:"1170–1340"});
Colleges2.insert({name:"University of Oklahoma", location:"South", SAT:"1130–1420"});
Colleges2.insert({name:"University of Richmond", location:"South", SAT:"1300–1480"});
Colleges2.insert({name:"University of South Carolina", location:"South", SAT:"1180–1370"});
Colleges2.insert({name:"University of South Florida", location:"South", SAT:"1150–1310"});
Colleges2.insert({name:"University of Tennessee", location:"South", SAT:"1120–1330"});
Colleges2.insert({name:"University of Texas— Austin", location:"South", SAT:"1220–1450"});
Colleges2.insert({name:"University of Texas— Dallas", location:"South", SAT:"1220–1430"});
Colleges2.insert({name:"University of Tulsa", location:"South", SAT:"1210–1470"});
Colleges2.insert({name:"University of Virginia", location:"South", SAT:"1320–1510"});
Colleges2.insert({name:"Vanderbilt University", location:"South", SAT:"1480–1590"});
Colleges2.insert({name:"Virginia Commonwealth University", location:"South", SAT:"1070–1260"});
Colleges2.insert({name:"Virginia Military Institute", location:"South", SAT:"1140–1310"});
Colleges2.insert({name:"Wake Forest University", location:"South", SAT:"1280–1480"});
Colleges2.insert({name:"Washington and Lee University", location:"South", SAT:"1390–1510"});
Colleges2.insert({name:"Washington University in St. Louis", location:"South", SAT:"1480–1580"});
Colleges2.insert({name:"Wofford College", location:"South", SAT:"1140–1340"});

Colleges2.insert({name:"Albion College", location:"Mid-West", SAT:"1090–1280"});
Colleges2.insert({name:"Augustana College", location:"Mid-West", SAT:"1120–1410"});
Colleges2.insert({name:"Baldwin Wallace University", location:"Mid-West", SAT:"1030–1270"});
Colleges2.insert({name:"Beloit College", location:"Mid-West", SAT:"1150–1410"});
Colleges2.insert({name:"Bradley University", location:"Mid-West", SAT:"1080–1330"});
Colleges2.insert({name:"Butler University", location:"Mid-West", SAT:"1130–1320"});
Colleges2.insert({name:"Carleton College", location:"Mid-West", SAT:"1390–1550"});
Colleges2.insert({name:"Case Western Reserve University", location:"Mid-West", SAT:"1350–1520"});
Colleges2.insert({name:"Coe College", location:"Mid-West", SAT:"1110–1330"});
Colleges2.insert({name:"College of St. Benedict", location:"Mid-West", SAT:"1070–1310"});
Colleges2.insert({name:"College of Wooster", location:"Mid-West", SAT:"1180–1400"});
Colleges2.insert({name:"Concordia College— Moorhead", location:"Mid-West", SAT:"1290–1390"});
Colleges2.insert({name:"Cornell College", location:"Mid-West", SAT:"1110–1370"});
Colleges2.insert({name:"Creighton University", location:"Mid-West", SAT:"1140–1350"});
Colleges2.insert({name:"Denison University", location:"Mid-West", SAT:"1230–1460"});
Colleges2.insert({name:"DePaul University", location:"Mid-West", SAT:"1080–1290"});
Colleges2.insert({name:"DePauw University", location:"Mid-West", SAT:"1140–1370"});
Colleges2.insert({name:"Drake University", location:"Mid-West", SAT:"1140–1380"});
Colleges2.insert({name:"Drury University", location:"Mid-West", SAT:"1110–1330"});
Colleges2.insert({name:"Earlham College", location:"Mid-West", SAT:"1180–1450"});
Colleges2.insert({name:"Elmhurst College", location:"Mid-West", SAT:"1000–1300"});
Colleges2.insert({name:"Goshen College", location:"Mid-West", SAT:"1040–1320"});
Colleges2.insert({name:"Grinnell College", location:"Mid-West", SAT:"1370–1540"});
Colleges2.insert({name:"Gustavus Adolphus College", location:"Mid-West", SAT:"1170–1430"});
Colleges2.insert({name:"Hanover College", location:"Mid-West", SAT:"1020–1230"});
Colleges2.insert({name:"Hillsdale College", location:"Mid-West", SAT:"1270–1460"});
Colleges2.insert({name:"Hope College", location:"Mid-West", SAT:"1150–1400"});
Colleges2.insert({name:"Illinois Institute of Technology", location:"Mid-West", SAT:"1230–1450"});
Colleges2.insert({name:"Illinois Wesleyan University", location:"Mid-West", SAT:"1230–1440"});
Colleges2.insert({name:"Indiana University— Bloomington", location:"Mid-West", SAT:"1140–1370"});
Colleges2.insert({name:"Iowa State University", location:"Mid-West", SAT:"1030–1320"});
Colleges2.insert({name:"Kalamazoo College", location:"Mid-West", SAT:"1150–1420"});
Colleges2.insert({name:"Kenyon College", location:"Mid-West", SAT:"1310–1470"});
Colleges2.insert({name:"Knox College", location:"Mid-West", SAT:"1250–1370"});
Colleges2.insert({name:"Lake Forest College", location:"Mid-West", SAT:"1080–1320"});
Colleges2.insert({name:"Lawrence University", location:"Mid-West", SAT:"1210–1470"});
Colleges2.insert({name:"Loyola University Chicago", location:"Mid-West", SAT:"1130–1330"});
Colleges2.insert({name:"Luther College", location:"Mid-West", SAT:"1050–1330"});
Colleges2.insert({name:"Macalester College", location:"Mid-West", SAT:"1320–1510"});
Colleges2.insert({name:"Marquette University", location:"Mid-West", SAT:"1150–1380"});
Colleges2.insert({name:"Miami University— Oxford", location:"Mid-West", SAT:"1210–1420"});
Colleges2.insert({name:"Michigan State University", location:"Mid-West", SAT:"1070–1350"});

Colleges2.insert({name:"Michigan Technological University", location:"Mid-West", SAT:"1160–1410"});
Colleges2.insert({name:"Milwaukee School of Engineering", location:"Mid-West", SAT:"1200–1430"});
Colleges2.insert({name:"Missouri University of Science & Technology", location:"Mid-West", SAT:"1140–1360"});
Colleges2.insert({name:"Northwestern University", location:"Mid-West", SAT:"1480–1580"});
Colleges2.insert({name:"Oberlin College", location:"Mid-West", SAT:"1330–1500"});
Colleges2.insert({name:"Ohio State University— Columbus", location:"Mid-West", SAT:"1250–1460"});
Colleges2.insert({name:"Ohio University", location:"Mid-West", SAT:"1070–1280"});
Colleges2.insert({name:"Ohio Wesleyan University", location:"Mid-West", SAT:"1080–1290"});
Colleges2.insert({name:"Purdue University— West Lafayette", location:"Mid-West", SAT:"1160–1410"});
Colleges2.insert({name:"Ripon College", location:"Mid-West", SAT:"1050–1390"});
Colleges2.insert({name:"Saint Louis University", location:"Mid-West", SAT:"1150–1400"});
Colleges2.insert({name:"St. Mary's College (IN)", location:"Mid-West", SAT:"1070–1280"});
Colleges2.insert({name:"St. Olaf College", location:"Mid-West", SAT:"1200–1470"});
Colleges2.insert({name:"Taylor University", location:"Mid-West", SAT:"1080–1320"});
Colleges2.insert({name:"Truman State University", location:"Mid-West", SAT:"1200–1450"});
Colleges2.insert({name:"University of Chicago", location:"Mid-West", SAT:"1480–1600"});
Colleges2.insert({name:"University of Cincinnati", location:"Mid-West", SAT:"1120–1370"});
Colleges2.insert({name:"University of Dayton", location:"Mid-West", SAT:"1130–1320"});
Colleges2.insert({name:"University of Illinois— Chicago", location:"Mid-West", SAT:"1090–1330"});
Colleges2.insert({name:"University of Illinois— Urbana- Champaign", location:"Mid-West", SAT:"1380–1530"});
Colleges2.insert({name:"University of Iowa", location:"Mid-West", SAT:"1070–1400"});
Colleges2.insert({name:"University of Kansas", location:"Mid-West", SAT:"N/A"});
Colleges2.insert({name:"University of Michigan— Ann Arbor", location:"Mid-West", SAT:"1370–1530"});
Colleges2.insert({name:"University of Minnesota— Twin Cities", location:"Mid-West", SAT:"1260–1490"});
Colleges2.insert({name:"University of Missouri", location:"Mid-West", SAT:"1140–1370"});
Colleges2.insert({name:"University of Nebraska— Lincoln", location:"Mid-West", SAT:"1070–1370"});
Colleges2.insert({name:"University of Notre Dame", location:"Mid-West", SAT:"1410–1550"});
Colleges2.insert({name:"University of St. Thomas (MN)", location:"Mid-West", SAT:"1140–1380"});
Colleges2.insert({name:"University of Wisconsin— Madison", location:"Mid-West", SAT:"1290–1490"});
Colleges2.insert({name:"Valparaiso University", location:"Mid-West", SAT:"1080–1290"});
Colleges2.insert({name:"Wabash College", location:"Mid-West", SAT:"1090–1310"});
Colleges2.insert({name:"Wheaton College (IL)", location:"Mid-West", SAT:"1170–1390"});
Colleges2.insert({name:"Xavier University", location:"Mid-West", SAT:"1060–1260"});

Colleges2.insert({name:"Arizona State University— Tempe", location:"West", SAT:"1110–1340"});
Colleges2.insert({name:"Biola University", location:"West", SAT:"1070–1310"});
Colleges2.insert({name:"Brigham Young University— Provo", location:"West", SAT:"1220–1420"});
Colleges2.insert({name:"California Institute of Technology", location:"West", SAT:"1530–1600"});
Colleges2.insert({name:"California Lutheran University", location:"West", SAT:"1090–1270"});
Colleges2.insert({name:"Cal Poly— San Luis Obispo", location:"West", SAT:"1200–1420"});
Colleges2.insert({name:"Cal Poly—Pomona", location:"West", SAT:"1010–1250"});
Colleges2.insert({name:"California State University—Fresno", location:"West", SAT:" 880–1090"});
Colleges2.insert({name:"California State University—Fullerton", location:"West", SAT:"1010–1200"});
Colleges2.insert({name:"California State University—Long Beach", location:"West", SAT:"1010–1240"});
Colleges2.insert({name:"California State University—Los Angeles", location:"West", SAT:" 870–1070"});
Colleges2.insert({name:"California State University—Monterey Bay", location:"West", SAT:" 940–1170"});
Colleges2.insert({name:"California State University—Northridge", location:"West", SAT:" 880–1110"});
Colleges2.insert({name:"Carroll College", location:"West", SAT:"1070–1310"});
Colleges2.insert({name:"Chapman University", location:"West", SAT:"1190–1370"});
Colleges2.insert({name:"Claremont McKenna College", location:"West", SAT:"1420–1560"});
Colleges2.insert({name:"Colorado College", location:"West", SAT:"1320–1480"});
Colleges2.insert({name:"Colorado School of Mines", location:"West", SAT:"1310–1470"});
Colleges2.insert({name:"Colorado State University", location:"West", SAT:"1110–1310"});
Colleges2.insert({name:"Gonzaga University", location:"West", SAT:"1150–1350"});
Colleges2.insert({name:"Harvey Mudd College", location:"West", SAT:"1470–1570"});
Colleges2.insert({name:"Humboldt State University", location:"West", SAT:" 960–1180"});
Colleges2.insert({name:"Lewis & Clark College", location:"West", SAT:"1260–1410"});
Colleges2.insert({name:"Loyola Marymount University", location:"West", SAT:"1190–1380"});
Colleges2.insert({name:"Mills College", location:"West", SAT:"1120–1340"});
Colleges2.insert({name:"Occidental College", location:"West", SAT:"1280–1450"});
Colleges2.insert({name:"Oregon State University", location:"West", SAT:"1060–1290"});
Colleges2.insert({name:"Pacific Lutheran University", location:"West", SAT:"1060–1270"});
Colleges2.insert({name:"Pepperdine University", location:"West", SAT:"1180–1400"});
Colleges2.insert({name:"Pitzer College", location:"West", SAT:"1310–1510"});
Colleges2.insert({name:"Point Loma Nazarene University", location:"West", SAT:"1100–1290"});
Colleges2.insert({name:"Pomona College", location:"West", SAT:"1430–1560"});
Colleges2.insert({name:"Reed College", location:"West", SAT:"1340–1510"});
Colleges2.insert({name:"San Diego State University", location:"West", SAT:"1090–1300"});
Colleges2.insert({name:"San Francisco State University", location:"West", SAT:" 950–1150"});
Colleges2.insert({name:"San Jose State University", location:"West", SAT:"1010–1250"});
Colleges2.insert({name:"Santa Clara University", location:"West", SAT:"1280–1480"});
Colleges2.insert({name:"Scripps College", location:"West", SAT:"1330–1500"});
Colleges2.insert({name:"Seattle University", location:"West", SAT:"1150–1340"});
Colleges2.insert({name:"Soka University of America", location:"West", SAT:"1180–1440"});
Colleges2.insert({name:"St. Mary's College of California", location:"West", SAT:"1120–1310"});
Colleges2.insert({name:"Stanford University", location:"West", SAT:"1460–1590"});

Colleges2.insert({name:"Thomas Aquinas College", location:"West", SAT:"1240–1390"});
Colleges2.insert({name:"United States Air Force Academy", location:"West", SAT:"1280–1460"});
Colleges2.insert({name:"University of Arizona", location:"West", SAT:"1040–1290"});
Colleges2.insert({name:"University of California— Berkeley", location:"West", SAT:"1330–1540"});
Colleges2.insert({name:"University of California— Davis", location:"West", SAT:"1160–1430"});
Colleges2.insert({name:"University of California— Irvine", location:"West", SAT:"1130–1390"});
Colleges2.insert({name:"University of California— Los Angeles", location:"West", SAT:"1280–1520"});
Colleges2.insert({name:"University of California—Merced", location:"West", SAT:"1000–1210"});
Colleges2.insert({name:"University of California—Riverside", location:"West", SAT:"1110–1330"});
Colleges2.insert({name:"University of California— San Diego", location:"West", SAT:"1270–1490"});
Colleges2.insert({name:"University of California— Santa Barbara", location:"West", SAT:"1210–1440"});
Colleges2.insert({name:"University of California— Santa Cruz", location:"West", SAT:"1150–1390"});
Colleges2.insert({name:"University of Colorado— Boulder", location:"West", SAT:"1150–1370"});
Colleges2.insert({name:"University of Denver", location:"West", SAT:"1180–1380"});
Colleges2.insert({name:"University of Hawaii at Manoa", location:"West", SAT:"1060–1260"});
Colleges2.insert({name:"University of La Verne", location:"West", SAT:"1020–1170"});
Colleges2.insert({name:"University of Oregon", location:"West", SAT:"1080–1290"});
Colleges2.insert({name:"University of Portland", location:"West", SAT:"1150–1370"});
Colleges2.insert({name:"University of Puget Sound", location:"West", SAT:"1180–1400"});
Colleges2.insert({name:"University of Redlands", location:"West", SAT:"1070–1260"});
Colleges2.insert({name:"University of San Diego", location:"West", SAT:"1180–1390"});
Colleges2.insert({name:"University of San Francisco", location:"West", SAT:"1130–1320"});
Colleges2.insert({name:"University of Southern California", location:"West", SAT:"1370–1530"});
Colleges2.insert({name:"University of the Pacific", location:"West", SAT:"1100–1370"});
Colleges2.insert({name:"University of Utah", location:"West", SAT:"1090–1370"});
Colleges2.insert({name:"University of Washington", location:"West", SAT:"1190–1440"});
Colleges2.insert({name:"Washington State University", location:"West", SAT:" 990–1200"});
Colleges2.insert({name:"Westmont College", location:"West", SAT:"1140–1360"});
Colleges2.insert({name:"Whitman College", location:"West", SAT:"1280–1470"});
Colleges2.insert({name:"Whittier College", location:"West", SAT:"1050–1250"});
Colleges2.insert({name:"Willamette University", location:"West", SAT:"1170–1370"});*/


 /*Colleges2.remove({name:"Amherst College", location:"New England", SAT:"1430–1570"});
Colleges2.remove({name:"Babson College", location:"New England", SAT:"1260–1450"});
Colleges2.remove({name:"Bates College", location:"New England", SAT:"1270–1470"});
Colleges2.remove({name:"Bennington College", location:"New England", SAT:"1230–1440"});
Colleges2.remove({name:"Bentley University", location:"New England", SAT:"1230–1410"});
Colleges2.remove({name:"Boston College", location:"New England", SAT:"1340–1510"});
Colleges2.remove({name:"Boston University", location:"New England", SAT:"1290–1480"});
Colleges2.remove({name:"Bowdoin College", location:"New England", SAT:"1450–1560"});
Colleges2.remove({name:"Brandeis University", location:"New England", SAT:"1360–1520"});
Colleges2.remove({name:"Brown University", location:"New England", SAT:"1440–1580"});
Colleges2.remove({name:"Clark University", location:"New England", SAT:"1260–1410"});
Colleges2.remove({name:"Colby College", location:"New England", SAT:"1310–1490"});
Colleges2.remove({name:"College of the Holy Cross", location:"New England", SAT:"1300–1450"});
Colleges2.remove({name:"Connecticut College", location:"New England", SAT:"1290–1460"});
Colleges2.remove({name:"Dartmouth College", location:"New England", SAT:"1410–1580"});
Colleges2.remove({name:"Emerson College", location:"New England", SAT:"1220–1380"});
Colleges2.remove({name:"Fairfield University", location:"New England", SAT:"1180–1340"});
Colleges2.remove({name:"Harvard University", location:"New England", SAT:"1480–1600"});
Colleges2.remove({name:"Massachusetts Institute of Technology", location:"New England", SAT:"1480–1580"});
Colleges2.remove({name:"Middlebury College", location:"New England", SAT:"1340–1520"});
Colleges2.remove({name:"Mount Holyoke College", location:"New England", SAT:"1310–1510"});
Colleges2.remove({name:"Northeastern University", location:"New England", SAT:"1410–1540"});
Colleges2.remove({name:"Providence College", location:"New England", SAT:"1140–1330"});
Colleges2.remove({name:"Quinnipiac University", location:"New England", SAT:"1100–1290"});
Colleges2.remove({name:"Rhode Island School of Design", location:"New England", SAT:"1200–1460"});
Colleges2.remove({name:"Simmons College", location:"New England", SAT:"1160–1330"});
Colleges2.remove({name:"Smith College", location:"New England", SAT:"1320–1500"});
Colleges2.remove({name:"St. Michael's College", location:"New England", SAT:"1150–1330"});
Colleges2.remove({name:"Stonehill College", location:"New England", SAT:"1100–1300"});
Colleges2.remove({name:"Trinity College (Hartford)", location:"New England", SAT:"1230–1420"});
Colleges2.remove({name:"Tufts University", location:"New England", SAT:"1440–1550"});
Colleges2.remove({name:"United States Coast Guard Academy", location:"New England", SAT:"1250–1410"});
Colleges2.remove({name:"University of Connecticut", location:"New England", SAT:"1220–1420"});
Colleges2.remove({name:"University of Massachusetts— Amherst", location:"New England", SAT:"1200–1380"});
Colleges2.remove({name:"University of New Hampshire", location:"New England", SAT:"1090–1280"});
Colleges2.remove({name:"University of Vermont", location:"New England", SAT:"1170–1360"});
Colleges2.remove({name:"Wellesley College", location:"New England", SAT:"1360–1530"});
Colleges2.remove({name:"Wesleyan University", location:"New England", SAT:"1330–1520"});
Colleges2.remove({name:"Williams College", location:"New England", SAT:"1410–1570"});
Colleges2.remove({name:"Worcester Polytechnic Institute", location:"New England", SAT:"1290–1470"});
Colleges2.remove({name:"Yale University", location:"New England", SAT:"1480–1600"});

Colleges2.remove({name:"Adelphi University", location:"Mid-Atlantic", SAT:"1100–1300"});
Colleges2.remove({name:"Allegheny College", location:"Mid-Atlantic", SAT:"1130–1340"});
Colleges2.remove({name:"American University", location:"Mid-Atlantic", SAT:"1220–1390"});
Colleges2.remove({name:"Bard College", location:"Mid-Atlantic", SAT:"1230–1450"});
Colleges2.remove({name:"Barnard College", location:"Mid-Atlantic", SAT:"1330–1490"});
Colleges2.remove({name:"Binghamton University— SUNY", location:"Mid-Atlantic", SAT:"1280–1440"});
Colleges2.remove({name:"Bryn Mawr College", location:"Mid-Atlantic", SAT:"1320–1510"});
Colleges2.remove({name:"Bucknell University", location:"Mid-Atlantic", SAT:"1290–1460"});
Colleges2.remove({name:"Carnegie Mellon University", location:"Mid-Atlantic", SAT:"1440–1570"});
Colleges2.remove({name:"Clarkson University", location:"Mid-Atlantic", SAT:"1160–1360"});
Colleges2.remove({name:"Colgate University", location:"Mid-Atlantic", SAT:"1310–1520"});
Colleges2.remove({name:"College of New Jersey", location:"Mid-Atlantic", SAT:"1200–1400"});
Colleges2.remove({name:"Columbia University", location:"Mid-Atlantic", SAT:"1460–1590"});
Colleges2.remove({name:"Cooper Union", location:"Mid-Atlantic", SAT:"1330–1530"});
Colleges2.remove({name:"Cornell University", location:"Mid-Atlantic", SAT:"1410–1570"});
Colleges2.remove({name:"CUNY— Baruch College", location:"Mid-Atlantic", SAT:"1190–1400"});
Colleges2.remove({name:"Dickinson College", location:"Mid-Atlantic", SAT:"1270–1450"});
Colleges2.remove({name:"Drew University", location:"Mid-Atlantic", SAT:"1090–1290"});
Colleges2.remove({name:"Drexel University", location:"Mid-Atlantic", SAT:"1170–1390"});
Colleges2.remove({name:"Duquesne University", location:"Mid-Atlantic", SAT:"1120–1300"});
Colleges2.remove({name:"Fordham University", location:"Mid-Atlantic", SAT:"1230–1420"});
Colleges2.remove({name:"Franklin and Marshall College", location:"Mid-Atlantic", SAT:"1290–1460"});
Colleges2.remove({name:"Gallaudet University", location:"Mid-Atlantic", SAT:"870–1040"});
Colleges2.remove({name:"George Washington University", location:"Mid-Atlantic", SAT:"1270–1460"});
Colleges2.remove({name:"Georgetown University", location:"Mid-Atlantic", SAT:"1390–1560"});
Colleges2.remove({name:"Gettysburg College", location:"Mid-Atlantic", SAT:"1270–1430"});
Colleges2.remove({name:"Goucher College", location:"Mid-Atlantic", SAT:"1070–1290"});
Colleges2.remove({name:"Hamilton College", location:"Mid-Atlantic", SAT:"1370–1520"});
Colleges2.remove({name:"Haverford College", location:"Mid-Atlantic", SAT:"1400–1560"});
Colleges2.remove({name:"Hobart and William Smith Colleges2", location:"Mid-Atlantic", SAT:"1200–1390"});
Colleges2.remove({name:"Hofstra University", location:"Mid-Atlantic", SAT:"1120–1300"});
Colleges2.remove({name:"Howard University", location:"Mid-Atlantic", SAT:"1070–1290"});
Colleges2.remove({name:"Ithaca College", location:"Mid-Atlantic", SAT:"1170–1360"});
Colleges2.remove({name:"Johns Hopkins University", location:"Mid-Atlantic", SAT:"1470–1580"});
Colleges2.remove({name:"Lafayette College", location:"Mid-Atlantic", SAT:"1280–1460"});
Colleges2.remove({name:"Lehigh University", location:"Mid-Atlantic", SAT:"1300–1480"});
Colleges2.remove({name:"Loyola University Maryland", location:"Mid-Atlantic", SAT:"1180–1360"});
Colleges2.remove({name:"Marist College", location:"Mid-Atlantic", SAT:"1170–1340"});
Colleges2.remove({name:"Muhlenberg College", location:"Mid-Atlantic", SAT:"1200–1410"});
Colleges2.remove({name:"New Jersey Institute of Technology", location:"Mid-Atlantic", SAT:"1150–1380"});
Colleges2.remove({name:"New School", location:"Mid-Atlantic", SAT:"1080–1320"});
Colleges2.remove({name:"New York University", location:"Mid-Atlantic", SAT:"1320-1500"});

Colleges2.remove({name:"Penn State University— University Park", location:"Mid-Atlantic", SAT:"1170–1380"});
Colleges2.remove({name:"Pratt Institute", location:"Mid-Atlantic", SAT:"1150–1370"});
Colleges2.remove({name:"Princeton University", location:"Mid-Atlantic", SAT:"1460–1600"});
Colleges2.remove({name:"Rensselaer Polytechnic Institute", location:"Mid-Atlantic", SAT:"1370–1540"});
Colleges2.remove({name:"Rochester Institute of Technology", location:"Mid-Atlantic", SAT:"1180–1390"});
Colleges2.remove({name:"Rutgers— New Brunswick", location:"Mid-Atlantic", SAT:"1180–1400"});
Colleges2.remove({name:"Rutgers— Newark", location:"Mid-Atlantic", SAT:"1030–1210"});
Colleges2.remove({name:"Sarah Lawrence College", location:"Mid-Atlantic", SAT:"1230–1430"});
Colleges2.remove({name:"Seton Hall University", location:"Mid-Atlantic", SAT:"1120–1300"});
Colleges2.remove({name:"Siena College", location:"Mid-Atlantic", SAT:"1100–1290"});
Colleges2.remove({name:"Skidmore College", location:"Mid-Atlantic", SAT:"1190–1410"});
Colleges2.remove({name:"St. John Fisher College", location:"Mid-Atlantic", SAT:"1080–1240"});
Colleges2.remove({name:"St. John's College Annapolis", location:"Mid-Atlantic", SAT:"1260–1470"});
Colleges2.remove({name:"St. John's University (NY)", location:"Mid-Atlantic", SAT:"1030–1240"});
Colleges2.remove({name:"St. Lawrence University", location:"Mid-Atlantic", SAT:"1170–1380"});
Colleges2.remove({name:"St. Mary's College of Maryland", location:"Mid-Atlantic", SAT:"1110–1320"});
Colleges2.remove({name:"Stevens Institute of Technology", location:"Mid-Atlantic", SAT:"1330–1480"});
Colleges2.remove({name:"Stony Brook University— SUNY", location:"Mid-Atlantic", SAT:"1220–1450"});
Colleges2.remove({name:"SUNY—Environmental Science and Forestry", location:"Mid-Atlantic", SAT:"1160–1340"});
Colleges2.remove({name:"SUNY— Geneseo", location:"Mid-Atlantic", SAT:"1170–1350"});
Colleges2.remove({name:"Susquehanna University", location:"Mid-Atlantic", SAT:"1100–1280"});
Colleges2.remove({name:"Swarthmore College", location:"Mid-Atlantic", SAT:"1420–1560"});
Colleges2.remove({name:"Syracuse University", location:"Mid-Atlantic", SAT:"1150–1370"});
Colleges2.remove({name:"Temple University", location:"Mid-Atlantic", SAT:"1090–1300"});
Colleges2.remove({name:"The Catholic University of America", location:"Mid-Atlantic", SAT:"1100–1290"});
Colleges2.remove({name:"Union College (Schenectady, NY)", location:"Mid-Atlantic", SAT:"1310–1470"});
Colleges2.remove({name:"United States Military Academy", location:"Mid-Atlantic", SAT:"1240–1440"});
Colleges2.remove({name:"United States Naval Academy", location:"Mid-Atlantic", SAT:"1250–1460"});
Colleges2.remove({name:"University at Albany— SUNY", location:"Mid-Atlantic", SAT:"1090–1240"});
Colleges2.remove({name:"University at Buffalo— SUNY", location:"Mid-Atlantic", SAT:"1110–1310"});
Colleges2.remove({name:"University of Delaware", location:"Mid-Atlantic", SAT:"1180–1380"});
Colleges2.remove({name:"University of Maryland— College Park", location:"Mid-Atlantic", SAT:"1280–1500"});
Colleges2.remove({name:"University of Pennsylvania", location:"Mid-Atlantic", SAT:"1450–1580"});
Colleges2.remove({name:"University of Pittsburgh", location:"Mid-Atlantic", SAT:"1250–1430"});
Colleges2.remove({name:"University of Rochester", location:"Mid-Atlantic", SAT:"1320–1500"});
Colleges2.remove({name:"Ursinus College", location:"Mid-Atlantic", SAT:"1130–1330"});
Colleges2.remove({name:"Vassar College", location:"Mid-Atlantic", SAT:"1400–1530"});
Colleges2.remove({name:"Villanova University", location:"Mid-Atlantic", SAT:"1280–1470"});
Colleges2.remove({name:"Virginia Polytechnic Institute", location:"Mid-Atlantic", SAT:"1180–1390"});
Colleges2.remove({name:"Washington and Jefferson College", location:"Mid-Atlantic", SAT:"1110–1300"});
Colleges2.remove({name:"Washington College", location:"Mid-Atlantic", SAT:"1120–1340"});
Colleges2.remove({name:"Yeshiva University", location:"Mid-Atlantic", SAT:"1190–1420"});

Colleges2.remove({name:"Abilene Christian University", location:"South", SAT:"1070–1270"});
Colleges2.remove({name:"Agnes Scott College", location:"South", SAT:"1150–1380"});
Colleges2.remove({name:"Appalachian State University", location:"South", SAT:"1130–1300"});
Colleges2.remove({name:"Auburn University", location:"South", SAT:"1140–1320"});
Colleges2.remove({name:"Austin College", location:"South", SAT:"1150–1350"});
Colleges2.remove({name:"Baylor University", location:"South", SAT:"1200–1390"});
Colleges2.remove({name:"Berea College", location:"South", SAT:"1110–1290"});
Colleges2.remove({name:"Berry College", location:"South", SAT:"1140–1330"});
Colleges2.remove({name:"Birmingham– Southern College", location:"South", SAT:"1070–1300"});
Colleges2.remove({name:"Centre College", location:"South", SAT:"1170–1460"});
Colleges2.remove({name:"Christopher Newport University", location:"South", SAT:"1140–1320"});
Colleges2.remove({name:"Clemson University", location:"South", SAT:"1230–1420"});
Colleges2.remove({name:"College of Charleston", location:"South", SAT:"1100–1290"});
Colleges2.remove({name:"College of William and Mary", location:"South", SAT:"1330–1510"});
Colleges2.remove({name:"Davidson College", location:"South", SAT:"1320–1500"});
Colleges2.remove({name:"Duke University", location:"South", SAT:"1450–1580"});
Colleges2.remove({name:"Elon University", location:"South", SAT:"1210–1390"});
Colleges2.remove({name:"Embry– Riddle Aeronautical University", location:"South", SAT:"1090–1310"});
Colleges2.remove({name:"Emory University", location:"South", SAT:"1360–1520"});
Colleges2.remove({name:"Florida Institute of Technology", location:"South", SAT:"1100–1330"});
Colleges2.remove({name:"Florida State University", location:"South", SAT:"1200–1350"});
Colleges2.remove({name:"Furman University", location:"South", SAT:"1210–1410"});
Colleges2.remove({name:"George Mason University", location:"South", SAT:"1120–1310"});
Colleges2.remove({name:"Georgia Institute of Technology", location:"South", SAT:"1390–1530"});
Colleges2.remove({name:"Hampden– Sydney College", location:"South", SAT:"1070–1270"});
Colleges2.remove({name:"Hampton University", location:"South", SAT:"990–1170"});
Colleges2.remove({name:"Hendrix College", location:"South", SAT:"1150–1390"});
Colleges2.remove({name:"High Point University", location:"South", SAT:"1090–1270"});
Colleges2.remove({name:"Hollins University", location:"South", SAT:"1050–1250"});
Colleges2.remove({name:"James Madison University", location:"South", SAT:"1120–1300"});
Colleges2.remove({name:"John Brown University", location:"South", SAT:"1100–1310"});
Colleges2.remove({name:"Lipscomb University", location:"South", SAT:"1110–1320"});
Colleges2.remove({name:"Louisiana State University— Baton Rouge", location:"South", SAT:"1100–1320"});
Colleges2.remove({name:"Loyola University New Orleans", location:"South", SAT:"1080–1300"});
Colleges2.remove({name:"Mercer University", location:"South", SAT:"1150–1350"});
Colleges2.remove({name:"Millsaps College", location:"South", SAT:"1110–1330"});
Colleges2.remove({name:"Mississippi State University", location:"South", SAT:"1030–1320"});
Colleges2.remove({name:"Morehouse College", location:"South", SAT:"970–1190"});
Colleges2.remove({name:"New College of Florida", location:"South", SAT:"1240–1430"});
Colleges2.remove({name:"North Carolina State University— Raleigh", location:"South", SAT:"1230–1400"});
Colleges2.remove({name:"Oklahoma State University", location:"South", SAT:"1060–1280"});
Colleges2.remove({name:"Presbyterian College (SC)", location:"South", SAT:"1040–1270"});
Colleges2.remove({name:"Queens University of Charlotte", location:"South", SAT:"1010–1230"});
Colleges2.remove({name:"Randolph– Macon College", location:"South", SAT:"1060–1260"});

Colleges2.remove({name:"Rhodes College", location:"South", SAT:"1260–1460"});
Colleges2.remove({name:"Rice University", location:"South", SAT:"1460–1580"});
Colleges2.remove({name:"Rollins College", location:"South", SAT:"1190–1390"});
Colleges2.remove({name:"Samford University", location:"South", SAT:"1090–1300"});
Colleges2.remove({name:"Sewanee— University of the South", location:"South", SAT:"1210–1380"});
Colleges2.remove({name:"Southern Methodist University", location:"South", SAT:"1290–1480"});
Colleges2.remove({name:"Southwestern University", location:"South", SAT:"1110–1330"});
Colleges2.remove({name:"Spelman College", location:"South", SAT:" 990–1180"});
Colleges2.remove({name:"Stetson University", location:"South", SAT:"1150–1320"});
Colleges2.remove({name:"Texas A&M University— College Station", location:"South", SAT:"1130–1380"});
Colleges2.remove({name:"Texas Christian University", location:"South", SAT:"1160–1350"});
Colleges2.remove({name:"Texas Lutheran University", location:"South", SAT:"1000–1200"});
Colleges2.remove({name:"The Citadel", location:"South", SAT:"1070–1260"});
Colleges2.remove({name:"Transylvania University", location:"South", SAT:"1120–1370"});
Colleges2.remove({name:"Trinity University", location:"South", SAT:"1230–1420"});
Colleges2.remove({name:"Tulane University", location:"South", SAT:"1320–1470"});
Colleges2.remove({name:"University of Alabama", location:"South", SAT:"1070–1310"});
Colleges2.remove({name:"University of Arkansas", location:"South", SAT:"1080–1300"});
Colleges2.remove({name:"University of Dallas", location:"South", SAT:"1220–1430"});
Colleges2.remove({name:"University of Florida", location:"South", SAT:"1250–1430"});
Colleges2.remove({name:"University of Georgia", location:"South", SAT:"1220–1400"});
Colleges2.remove({name:"University of Kentucky", location:"South", SAT:"1080–1330"});
Colleges2.remove({name:"University of Mary Washington", location:"South", SAT:"1090–1270"});
Colleges2.remove({name:"University of Miami", location:"South", SAT:"1270–1450"});
Colleges2.remove({name:"University of Mississippi", location:"South", SAT:"1040–1250"});
Colleges2.remove({name:"University of North Carolina— Chapel Hill", location:"South", SAT:"1280–1460"});
Colleges2.remove({name:"University of North Carolina— Wilmington", location:"South", SAT:"1170–1340"});
Colleges2.remove({name:"University of Oklahoma", location:"South", SAT:"1130–1420"});
Colleges2.remove({name:"University of Richmond", location:"South", SAT:"1300–1480"});
Colleges2.remove({name:"University of South Carolina", location:"South", SAT:"1180–1370"});
Colleges2.remove({name:"University of South Florida", location:"South", SAT:"1150–1310"});
Colleges2.remove({name:"University of Tennessee", location:"South", SAT:"1120–1330"});
Colleges2.remove({name:"University of Texas— Austin", location:"South", SAT:"1220–1450"});
Colleges2.remove({name:"University of Texas— Dallas", location:"South", SAT:"1220–1430"});
Colleges2.remove({name:"University of Tulsa", location:"South", SAT:"1210–1470"});
Colleges2.remove({name:"University of Virginia", location:"South", SAT:"1320–1510"});
Colleges2.remove({name:"Vanderbilt University", location:"South", SAT:"1480–1590"});
Colleges2.remove({name:"Virginia Commonwealth University", location:"South", SAT:"1070–1260"});
Colleges2.remove({name:"Virginia Military Institute", location:"South", SAT:"1140–1310"});
Colleges2.remove({name:"Wake Forest University", location:"South", SAT:"1280–1480"});
Colleges2.remove({name:"Washington and Lee University", location:"South", SAT:"1390–1510"});
Colleges2.remove({name:"Washington University in St. Louis", location:"South", SAT:"1480–1580"});
Colleges2.remove({name:"Wofford College", location:"South", SAT:"1140–1340"});

Colleges2.remove({name:"Albion College", location:"Mid-West", SAT:"1090–1280"});
Colleges2.remove({name:"Augustana College", location:"Mid-West", SAT:"1120–1410"});
Colleges2.remove({name:"Baldwin Wallace University", location:"Mid-West", SAT:"1030–1270"});
Colleges2.remove({name:"Beloit College", location:"Mid-West", SAT:"1150–1410"});
Colleges2.remove({name:"Bradley University", location:"Mid-West", SAT:"1080–1330"});
Colleges2.remove({name:"Butler University", location:"Mid-West", SAT:"1130–1320"});
Colleges2.remove({name:"Carleton College", location:"Mid-West", SAT:"1390–1550"});
Colleges2.remove({name:"Case Western Reserve University", location:"Mid-West", SAT:"1350–1520"});
Colleges2.remove({name:"Coe College", location:"Mid-West", SAT:"1110–1330"});
Colleges2.remove({name:"College of St. Benedict", location:"Mid-West", SAT:"1070–1310"});
Colleges2.remove({name:"College of Wooster", location:"Mid-West", SAT:"1180–1400"});
Colleges2.remove({name:"Concordia College— Moorhead", location:"Mid-West", SAT:"1290–1390"});
Colleges2.remove({name:"Cornell College", location:"Mid-West", SAT:"1110–1370"});
Colleges2.remove({name:"Creighton University", location:"Mid-West", SAT:"1140–1350"});
Colleges2.remove({name:"Denison University", location:"Mid-West", SAT:"1230–1460"});
Colleges2.remove({name:"DePaul University", location:"Mid-West", SAT:"1080–1290"});
Colleges2.remove({name:"DePauw University", location:"Mid-West", SAT:"1140–1370"});
Colleges2.remove({name:"Drake University", location:"Mid-West", SAT:"1140–1380"});
Colleges2.remove({name:"Drury University", location:"Mid-West", SAT:"1110–1330"});
Colleges2.remove({name:"Earlham College", location:"Mid-West", SAT:"1180–1450"});
Colleges2.remove({name:"Elmhurst College", location:"Mid-West", SAT:"1000–1300"});
Colleges2.remove({name:"Goshen College", location:"Mid-West", SAT:"1040–1320"});
Colleges2.remove({name:"Grinnell College", location:"Mid-West", SAT:"1370–1540"});
Colleges2.remove({name:"Gustavus Adolphus College", location:"Mid-West", SAT:"1170–1430"});
Colleges2.remove({name:"Hanover College", location:"Mid-West", SAT:"1020–1230"});
Colleges2.remove({name:"Hillsdale College", location:"Mid-West", SAT:"1270–1460"});
Colleges2.remove({name:"Hope College", location:"Mid-West", SAT:"1150–1400"});
Colleges2.remove({name:"Illinois Institute of Technology", location:"Mid-West", SAT:"1230–1450"});
Colleges2.remove({name:"Illinois Wesleyan University", location:"Mid-West", SAT:"1230–1440"});
Colleges2.remove({name:"Indiana University— Bloomington", location:"Mid-West", SAT:"1140–1370"});
Colleges2.remove({name:"Iowa State University", location:"Mid-West", SAT:"1030–1320"});
Colleges2.remove({name:"Kalamazoo College", location:"Mid-West", SAT:"1150–1420"});
Colleges2.remove({name:"Kenyon College", location:"Mid-West", SAT:"1310–1470"});
Colleges2.remove({name:"Knox College", location:"Mid-West", SAT:"1250–1370"});
Colleges2.remove({name:"Lake Forest College", location:"Mid-West", SAT:"1080–1320"});
Colleges2.remove({name:"Lawrence University", location:"Mid-West", SAT:"1210–1470"});
Colleges2.remove({name:"Loyola University Chicago", location:"Mid-West", SAT:"1130–1330"});
Colleges2.remove({name:"Luther College", location:"Mid-West", SAT:"1050–1330"});
Colleges2.remove({name:"Macalester College", location:"Mid-West", SAT:"1320–1510"});
Colleges2.remove({name:"Marquette University", location:"Mid-West", SAT:"1150–1380"});
Colleges2.remove({name:"Miami University— Oxford", location:"Mid-West", SAT:"1210–1420"});
Colleges2.remove({name:"Michigan State University", location:"Mid-West", SAT:"1070–1350"});

Colleges2.remove({name:"Michigan Technological University", location:"Mid-West", SAT:"1160–1410"});
Colleges2.remove({name:"Milwaukee School of Engineering", location:"Mid-West", SAT:"1200–1430"});
Colleges2.remove({name:"Missouri University of Science & Technology", location:"Mid-West", SAT:"1140–1360"});
Colleges2.remove({name:"Northwestern University", location:"Mid-West", SAT:"1480–1580"});
Colleges2.remove({name:"Oberlin College", location:"Mid-West", SAT:"1330–1500"});
Colleges2.remove({name:"Ohio State University— Columbus", location:"Mid-West", SAT:"1250–1460"});
Colleges2.remove({name:"Ohio University", location:"Mid-West", SAT:"1070–1280"});
Colleges2.remove({name:"Ohio Wesleyan University", location:"Mid-West", SAT:"1080–1290"});
Colleges2.remove({name:"Purdue University— West Lafayette", location:"Mid-West", SAT:"1160–1410"});
Colleges2.remove({name:"Ripon College", location:"Mid-West", SAT:"1050–1390"});
Colleges2.remove({name:"Saint Louis University", location:"Mid-West", SAT:"1150–1400"});
Colleges2.remove({name:"St. Mary's College (IN)", location:"Mid-West", SAT:"1070–1280"});
Colleges2.remove({name:"St. Olaf College", location:"Mid-West", SAT:"1200–1470"});
Colleges2.remove({name:"Taylor University", location:"Mid-West", SAT:"1080–1320"});
Colleges2.remove({name:"Truman State University", location:"Mid-West", SAT:"1200–1450"});
Colleges2.remove({name:"University of Chicago", location:"Mid-West", SAT:"1480–1600"});
Colleges2.remove({name:"University of Cincinnati", location:"Mid-West", SAT:"1120–1370"});
Colleges2.remove({name:"University of Dayton", location:"Mid-West", SAT:"1130–1320"});
Colleges2.remove({name:"University of Illinois— Chicago", location:"Mid-West", SAT:"1090–1330"});
Colleges2.remove({name:"University of Illinois— Urbana- Champaign", location:"Mid-West", SAT:"1380–1530"});
Colleges2.remove({name:"University of Iowa", location:"Mid-West", SAT:"1070–1400"});
Colleges2.remove({name:"University of Kansas", location:"Mid-West", SAT:"N/A"});
Colleges2.remove({name:"University of Michigan— Ann Arbor", location:"Mid-West", SAT:"1370–1530"});
Colleges2.remove({name:"University of Minnesota— Twin Cities", location:"Mid-West", SAT:"1260–1490"});
Colleges2.remove({name:"University of Missouri", location:"Mid-West", SAT:"1140–1370"});
Colleges2.remove({name:"University of Nebraska— Lincoln", location:"Mid-West", SAT:"1070–1370"});
Colleges2.remove({name:"University of Notre Dame", location:"Mid-West", SAT:"1410–1550"});
Colleges2.remove({name:"University of St. Thomas (MN)", location:"Mid-West", SAT:"1140–1380"});
Colleges2.remove({name:"University of Wisconsin— Madison", location:"Mid-West", SAT:"1290–1490"});
Colleges2.remove({name:"Valparaiso University", location:"Mid-West", SAT:"1080–1290"});
Colleges2.remove({name:"Wabash College", location:"Mid-West", SAT:"1090–1310"});
Colleges2.remove({name:"Wheaton College (IL)", location:"Mid-West", SAT:"1170–1390"});
Colleges2.remove({name:"Xavier University", location:"Mid-West", SAT:"1060–1260"});

Colleges2.remove({name:"Arizona State University— Tempe", location:"West", SAT:"1110–1340"});
Colleges2.remove({name:"Biola University", location:"West", SAT:"1070–1310"});
Colleges2.remove({name:"Brigham Young University— Provo", location:"West", SAT:"1220–1420"});
Colleges2.remove({name:"California Institute of Technology", location:"West", SAT:"1530–1600"});
Colleges2.remove({name:"California Lutheran University", location:"West", SAT:"1090–1270"});
Colleges2.remove({name:"Cal Poly— San Luis Obispo", location:"West", SAT:"1200–1420"});
Colleges2.remove({name:"Cal Poly—Pomona", location:"West", SAT:"1010–1250"});
Colleges2.remove({name:"California State University—Fresno", location:"West", SAT:" 880–1090"});
Colleges2.remove({name:"California State University—Fullerton", location:"West", SAT:"1010–1200"});
Colleges2.remove({name:"California State University—Long Beach", location:"West", SAT:"1010–1240"});
Colleges2.remove({name:"California State University—Los Angeles", location:"West", SAT:" 870–1070"});
Colleges2.remove({name:"California State University—Monterey Bay", location:"West", SAT:" 940–1170"});
Colleges2.remove({name:"California State University—Northridge", location:"West", SAT:" 880–1110"});
Colleges2.remove({name:"Carroll College", location:"West", SAT:"1070–1310"});
Colleges2.remove({name:"Chapman University", location:"West", SAT:"1190–1370"});
Colleges2.remove({name:"Claremont McKenna College", location:"West", SAT:"1420–1560"});
Colleges2.remove({name:"Colorado College", location:"West", SAT:"1320–1480"});
Colleges2.remove({name:"Colorado School of Mines", location:"West", SAT:"1310–1470"});
Colleges2.remove({name:"Colorado State University", location:"West", SAT:"1110–1310"});
Colleges2.remove({name:"Gonzaga University", location:"West", SAT:"1150–1350"});
Colleges2.remove({name:"Harvey Mudd College", location:"West", SAT:"1470–1570"});
Colleges2.remove({name:"Humboldt State University", location:"West", SAT:" 960–1180"});
Colleges2.remove({name:"Lewis & Clark College", location:"West", SAT:"1260–1410"});
Colleges2.remove({name:"Loyola Marymount University", location:"West", SAT:"1190–1380"});
Colleges2.remove({name:"Mills College", location:"West", SAT:"1120–1340"});
Colleges2.remove({name:"Occidental College", location:"West", SAT:"1280–1450"});
Colleges2.remove({name:"Oregon State University", location:"West", SAT:"1060–1290"});
Colleges2.remove({name:"Pacific Lutheran University", location:"West", SAT:"1060–1270"});
Colleges2.remove({name:"Pepperdine University", location:"West", SAT:"1180–1400"});
Colleges2.remove({name:"Pitzer College", location:"West", SAT:"1310–1510"});
Colleges2.remove({name:"Point Loma Nazarene University", location:"West", SAT:"1100–1290"});
Colleges2.remove({name:"Pomona College", location:"West", SAT:"1430–1560"});
Colleges2.remove({name:"Reed College", location:"West", SAT:"1340–1510"});
Colleges2.remove({name:"San Diego State University", location:"West", SAT:"1090–1300"});
Colleges2.remove({name:"San Francisco State University", location:"West", SAT:" 950–1150"});
Colleges2.remove({name:"San Jose State University", location:"West", SAT:"1010–1250"});
Colleges2.remove({name:"Santa Clara University", location:"West", SAT:"1280–1480"});
Colleges2.remove({name:"Scripps College", location:"West", SAT:"1330–1500"});
Colleges2.remove({name:"Seattle University", location:"West", SAT:"1150–1340"});
Colleges2.remove({name:"Soka University of America", location:"West", SAT:"1180–1440"});
Colleges2.remove({name:"St. Mary's College of California", location:"West", SAT:"1120–1310"});
Colleges2.remove({name:"Stanford University", location:"West", SAT:"1460–1590"});

Colleges2.remove({name:"Thomas Aquinas College", location:"West", SAT:"1240–1390"});
Colleges2.remove({name:"United States Air Force Academy", location:"West", SAT:"1280–1460"});
Colleges2.remove({name:"University of Arizona", location:"West", SAT:"1040–1290"});
Colleges2.remove({name:"University of California— Berkeley", location:"West", SAT:"1330–1540"});
Colleges2.remove({name:"University of California— Davis", location:"West", SAT:"1160–1430"});
Colleges2.remove({name:"University of California— Irvine", location:"West", SAT:"1130–1390"});
Colleges2.remove({name:"University of California— Los Angeles", location:"West", SAT:"1280–1520"});
Colleges2.remove({name:"University of California—Merced", location:"West", SAT:"1000–1210"});
Colleges2.remove({name:"University of California—Riverside", location:"West", SAT:"1110–1330"});
Colleges2.remove({name:"University of California— San Diego", location:"West", SAT:"1270–1490"});
Colleges2.remove({name:"University of California— Santa Barbara", location:"West", SAT:"1210–1440"});
Colleges2.remove({name:"University of California— Santa Cruz", location:"West", SAT:"1150–1390"});
Colleges2.remove({name:"University of Colorado— Boulder", location:"West", SAT:"1150–1370"});
Colleges2.remove({name:"University of Denver", location:"West", SAT:"1180–1380"});
Colleges2.remove({name:"University of Hawaii at Manoa", location:"West", SAT:"1060–1260"});
Colleges2.remove({name:"University of La Verne", location:"West", SAT:"1020–1170"});
Colleges2.remove({name:"University of Oregon", location:"West", SAT:"1080–1290"});
Colleges2.remove({name:"University of Portland", location:"West", SAT:"1150–1370"});
Colleges2.remove({name:"University of Puget Sound", location:"West", SAT:"1180–1400"});
Colleges2.remove({name:"University of Redlands", location:"West", SAT:"1070–1260"});
Colleges2.remove({name:"University of San Diego", location:"West", SAT:"1180–1390"});
Colleges2.remove({name:"University of San Francisco", location:"West", SAT:"1130–1320"});
Colleges2.remove({name:"University of Southern California", location:"West", SAT:"1370–1530"});
Colleges2.remove({name:"University of the Pacific", location:"West", SAT:"1100–1370"});
Colleges2.remove({name:"University of Utah", location:"West", SAT:"1090–1370"});
Colleges2.remove({name:"University of Washington", location:"West", SAT:"1190–1440"});
Colleges2.remove({name:"Washington State University", location:"West", SAT:" 990–1200"});
Colleges2.remove({name:"Westmont College", location:"West", SAT:"1140–1360"});
Colleges2.remove({name:"Whitman College", location:"West", SAT:"1280–1470"});
Colleges2.remove({name:"Whittier College", location:"West", SAT:"1050–1250"});
Colleges2.remove({name:"Willamette University", location:"West", SAT:"1170–1370"}); */

